#' Plot a nicheR Community of Ellipses
#'
#' @description
#' Visualizes a \code{nicheR_community} object by plotting the background
#' environmental space and the community of ellipses.
#'
#' @param object A \code{nicheR_community} object generated by one of the
#'   community simulation functions (e.g., \code{random_ellipses},
#'   \code{nested_ellipses}, \code{conserved_ellipses}).
#' @param background Matrix or Dataframe. The environmental background points.
#' @param dim Numeric vector of length 2. The indices of the variables to
#'   plot (default is \code{c(1, 2)}).
#' @param bg_sample Integer. Number of background points to sample for plotting.
#'   The default, NULL, plots all background points.
#' @param lty,lwd Numeric. Line type and width for community ellipses.
#' @param col_comm Character vector. Colors for the community ellipses.
#'   Defaults to a rainbow palette.
#' @param col_bg Character. Color for the background points.
#' @param pch Integer or point character for background points.
#' @param alpha_bg,alpha_comm Numeric. Transparency for background and ellipses.
#' @param cex_bg,cex_comm Numeric. Character expansion for points/lines.
#' @param ... Additional arguments passed to the base \code{plot} function
#'   (e.g., \code{xlim}, \code{ylim}, \code{xlab}, \code{ylab}).
#'
#'@importFrom grDevices rainbow
#'
#' @export

plot_community <- function(object,
                           background = NULL,
                           dim = c(1, 2),
                           bg_sample = NULL,
                           lty = 1,
                           lwd = 1,
                           col_comm = NULL,
                           col_bg = "#8A8A8A",
                           pch = 1,
                           alpha_bg = 1,
                           alpha_comm = 1,
                           cex_bg = 1,
                           cex_comm = 1,
                           ...) {

  # Check for error conditions
  if (missing(object) || !inherits(object, "nicheR_community")) {
    stop("Please provide a valid 'nicheR_community' object.")
  }
  if (!is.null(background) && !is.data.frame(background) &&
        !is.matrix(background)) {
    stop("Background must be a 'data.frame' or 'matrix'.")
  }

  # Setup Colors
  n_ell <- length(object$ellipse_community)
  if (is.null(col_comm)) {
    cols <- rainbow(n_ell)
  } else if (length(col_comm) == 1) {
    cols <- rep(col_comm, n_ell)
  } else {
    cols <- col_comm
  }

  # Extract variable names and calculate ellipse boundaries
  var_names <- object$reference$var_names[dim]

  # Calculate boundary points for ALL ellipses to determine plot limits
  all_ell_pts <- lapply(object$ellipse_community, function(ell) {
    ellipsoid_boundary_2d(object = ell, n_segments = 100, dim = dim)
  })

  # Combine all ellipse coordinates into one matrix for range calculation
  combined_ell_pts <- do.call(rbind, all_ell_pts)

  # Background sampling
  bg_sub <- NULL
  if (!is.null(background)) {
    bg_sub <- as.matrix(background[, var_names, drop = FALSE])

    if (!is.null(bg_sample) && nrow(bg_sub) > bg_sample) {
      bg_sub <- bg_sub[sample(seq_len(nrow(bg_sub)), bg_sample), ]
    }
  }

  # Build plot argument list
  plot_args <- list(...)
  if (!"xlim" %in% names(plot_args)) {
    plot_args$xlim <- range(c(combined_ell_pts[, 1], bg_sub[, 1]), na.rm = TRUE)
  }
  if (!"ylim" %in% names(plot_args)) {
    plot_args$ylim <- range(c(combined_ell_pts[, 2], bg_sub[, 2]), na.rm = TRUE)
  }
  if (!"xlab" %in% names(plot_args)) plot_args$xlab <- var_names[1]
  if (!"ylab" %in% names(plot_args)) plot_args$ylab <- var_names[2]

  # Execute Plot
  if (!is.null(background)) {
    plot_args$x <- bg_sub
    plot_args$col <- adjustcolor(col_bg, alpha.f = alpha_bg)
    plot_args$pch <- pch
    plot_args$cex <- cex_bg

    do.call(plot, plot_args)
  } else {
    plot_args$x <- NA
    plot_args$y <- NA
    plot_args$type <- "n"

    do.call(plot, plot_args)
  }

  # Add Ellipses
  for (i in seq_along(object$ellipse_community)) {
    add_ellipsoid(object$ellipse_community[[i]], dim = dim, col_ell = cols[i],
                  alpha_ell = alpha_comm, lwd = lwd, lty = lty,
                  cex_ell = cex_comm)
  }

  invisible(NULL)
}
